# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44235025a3578ea36d36c7b1933e31f343e8d5562a125129caa12bab5e052f43391d3c22300318836ec0d9f164c4ed5223fb04a0fd936a0aa8c6294bb8c2a2f2

test:
  secret_key_base: 5a25888692d5d24ba5b3ce8fc9d0be018bcb74b3b57bd03e87f4b4ce37990536df8846503e621873139c44edbcf6533bfd13974665a8150a3909d31d1f540595

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
